config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :posts, only: [:index, :show, :new, :create]

  mount RailsEventStore::Browser => '/res' if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def event_store
    Rails.configuration.event_store
  end

  def command_bus
    Rails.configuration.command_bus
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Posts::Post.all
  end

  def show
    @post = Posts::Post.find(params[:id])
  end

  def new
    @post = Posts::Post.new
  end

  def create
    cmd = Posting::CreatePost.new(
      post_params.to_h.symbolize_keys.merge(post_id: SecureRandom.uuid)
    )

    command_bus.(cmd)
    redirect_to(
      post_path(Posts::Post.find_by_uid(cmd.post_id)),
      notice: 'Post was successfully created.'
    )
  end


  private

  def post_params
    params.require(:posts_post).permit(:author, :title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def stream_browser_path(stream_name)
    "/res#streams/#{stream_name}"
  end

  def stream_browser_link(link_name, stream_name)
    link_to link_name, stream_browser_path(stream_name), data: { turbolinks: false }
  end

  def post_history_link(id)
    stream_browser_link("History", "Posting::Post$#{id}")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EsBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.slim
table
  tr
    th= "Title"
    th= "Author"
    th
    th

  - @posts.each do |post|
    tr
      td= post.title
      td= post.author
      td= post_history_link(post.uid)
      td= link_to 'Show', post_path(post)

p= link_to "New Post", new_post_path

app/views/posts/new.html.slim
= form_with model: @post, url: posts_path do |f|
  p
    = f.label :author, "Author"
    br
    = f.text_field :author

  p
    = f.label :title, "Title"
    br
    = f.text_field :title

  p
    = f.label :content, "Content"
    br
    = f.text_field :content

  = f.submit "Create Post"

app/views/posts/show.html.slim
h1= @post.title

strong= "By #{@post.author}"

p= @post.content

br
= link_to "All Posts", posts_path